version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.3.0
    commands:
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo Packaging the application...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.js
    - node_modules/**/*
    - package.json
  discard-paths: no
